name: 'Deploy to development'

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the docker image
        type: string

jobs:
  build_release:
    if: startsWith(github.head_ref, 'dependabot/pip/dev-dependencies') == false
    name: 'Build'
    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: write
    steps:
      - name: Move /var/lib/docker/
        run: sudo mv /var/lib/docker/ "${GITHUB_WORKSPACE}/docker"

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          build-mount-path: '/var/lib/docker/'

      - name: Restore /var/lib/docker/
        run: sudo sh -c "mv ${GITHUB_WORKSPACE}/docker/* /var/lib/docker"

      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Authenticate with Google Cloud'
        id: auth_gcp
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_REGISTRY_SA_CREDENTIALS }}'
          create_credentials_file: true

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 390.0.0'
          skip_install: true

      - name: 'Login to GCP Container Registry'
        run: gcloud auth configure-docker ${{ secrets.GOOGLE_ARTIFACTS_REGISTRY }}

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      - name: 'Build and push to Container Registry'
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: docker/Dockerfile
          build-args: |
            CARGO_PROFILE=production
          tags: |
            ${{ secrets.GOOGLE_ARTIFACTS_REGISTRY }}/${{ secrets.GOOGLE_ARTIFACTS_REGISTRY_PROJECT }}/${{ secrets.GOOGLE_ARTIFACTS_REPOSITORY }}/risingwave:${{ inputs.version }}
            ${{ secrets.GOOGLE_ARTIFACTS_REGISTRY }}/${{ secrets.GOOGLE_ARTIFACTS_REGISTRY_PROJECT }}/${{ secrets.GOOGLE_ARTIFACTS_REPOSITORY }}/risingwave:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max,compression=zstd
